import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

export type ChatRole = 'user' | 'assistant';

export type ChatMessage = {
  id: string;
  role: ChatRole;
  content: string;
};

export type ProjectFile = {
  path: string;
  content: string;
  language: string;
};

export type ChatHistoryItem = {
  id: string;
  description: string;
  createdAt: string;
  messages: ChatMessage[];
  files: ProjectFile[];
  previewHtml: string;
};

type ChatStoreValue = {
  chats: ChatHistoryItem[];
  activeChatId: string | null;
  messages: ChatMessage[];
  files: ProjectFile[];
  previewHtml: string;
  input: string;
  chatStarted: boolean;
  isStreaming: boolean;
  showChat: boolean;
  showWorkbench: boolean;
  selectedView: 'code' | 'preview';
  selectedFile: string | null;
  enhancingPrompt: boolean;
  promptEnhanced: boolean;
  sidebarOpen: boolean;
  description: string;
  setInput: (value: string) => void;
  setSidebarOpen: (open: boolean) => void;
  setShowChat: (show: boolean) => void;
  setShowWorkbench: (show: boolean) => void;
  setSelectedView: (view: 'code' | 'preview') => void;
  setSelectedFile: (path: string | null) => void;
  startNewChat: () => void;
  loadChat: (id: string) => void;
  deleteChat: (id: string) => void;
  enhancePrompt: () => Promise<void>;
  sendMessage: (text?: string) => Promise<void>;
  stopStreaming: () => void;
  updateFileContent: (path: string, content: string) => void;
};

const HISTORY_KEY = 'bolt_mobile_chats';

const EXAMPLE_APP_FILES: ProjectFile[] = [
  {
    path: '/App.tsx',
    language: 'tsx',
    content: `import React, { useState } from 'react';
import { SafeAreaView, StyleSheet, Text, TextInput, Pressable, FlatList, View } from 'react-native';

type Todo = { id: string; text: string; done: boolean };

export default function App() {
  const [text, setText] = useState('');
  const [todos, setTodos] = useState<Todo[]>([
    { id: '1', text: 'Ship Bolt mobile', done: false },
    { id: '2', text: 'Polish the workbench', done: true },
  ]);

  const addTodo = () => {
    if (!text.trim()) return;
    setTodos((current) => [{ id: Date.now().toString(), text: text.trim(), done: false }, ...current]);
    setText('');
  };

  return (
    <SafeAreaView style={styles.container}>
      <Text style={styles.title}>Bolt Todos</Text>
      <View style={styles.row}>
        <TextInput
          value={text}
          onChangeText={setText}
          placeholder="What needs doing?"
          placeholderTextColor="#737373"
          style={styles.input}
        />
        <Pressable onPress={addTodo} style={styles.button}>
          <Text style={styles.buttonText}>Add</Text>
        </Pressable>
      </View>
      <FlatList
        data={todos}
        keyExtractor={(item) => item.id}
        renderItem={({ item }) => (
          <Pressable
            onPress={() =>
              setTodos((current) =>
                current.map((todo) => (todo.id === item.id ? { ...todo, done: !todo.done } : todo)),
              )
            }
            style={styles.todo}
          >
            <Text style={[styles.todoText, item.done && styles.done]}>{item.text}</Text>
          </Pressable>
        )}
      />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0A0A0A', padding: 20 },
  title: { color: '#FFFFFF', fontSize: 32, fontWeight: '700', marginBottom: 16 },
  row: { flexDirection: 'row', gap: 8, marginBottom: 16 },
  input: {
    flex: 1,
    backgroundColor: '#171717',
    color: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  button: {
    backgroundColor: '#2BA6FF',
    borderRadius: 12,
    paddingHorizontal: 16,
    justifyContent: 'center',
  },
  buttonText: { color: '#FFFFFF', fontWeight: '600' },
  todo: {
    backgroundColor: '#171717',
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  todoText: { color: '#FFFFFF', fontSize: 16 },
  done: { textDecorationLine: 'line-through', color: '#737373' },
});
`,
  },
  {
    path: '/package.json',
    language: 'json',
    content: `{
  "name": "bolt-todo-app",
  "version": "1.0.0",
  "main": "expo/AppEntry.js",
  "dependencies": {
    "expo": "~57.0.0",
    "react": "19.2.3",
    "react-native": "0.86.2"
  }
}
`,
  },
  {
    path: '/README.md',
    language: 'markdown',
    content: `# Bolt Todo App

Generated by Bolt mobile — prompt, edit, and preview full-stack ideas on your phone.
`,
  },
];

const PREVIEW_HTML = `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      :root { color-scheme: dark; }
      * { box-sizing: border-box; }
      body {
        margin: 0;
        font-family: Inter, system-ui, -apple-system, sans-serif;
        background: #0A0A0A;
        color: #fff;
        padding: 20px;
      }
      h1 { font-size: 28px; margin: 0 0 16px; }
      .row { display: flex; gap: 8px; margin-bottom: 16px; }
      input {
        flex: 1;
        background: #171717;
        color: #fff;
        border: 1px solid rgba(255,255,255,0.1);
        border-radius: 12px;
        padding: 12px 14px;
      }
      button {
        background: #2BA6FF;
        color: #fff;
        border: 0;
        border-radius: 12px;
        padding: 0 16px;
        font-weight: 600;
      }
      .todo {
        background: #171717;
        border: 1px solid rgba(255,255,255,0.08);
        border-radius: 12px;
        padding: 14px;
        margin-bottom: 8px;
        cursor: pointer;
      }
      .done { text-decoration: line-through; color: #737373; }
    </style>
  </head>
  <body>
    <h1>Bolt Todos</h1>
    <div class="row">
      <input id="input" placeholder="What needs doing?" />
      <button id="add">Add</button>
    </div>
    <div id="list"></div>
    <script>
      const todos = [
        { id: '1', text: 'Ship Bolt mobile', done: false },
        { id: '2', text: 'Polish the workbench', done: true },
      ];
      const list = document.getElementById('list');
      const input = document.getElementById('input');
      function render() {
        list.innerHTML = todos.map((t) =>
          '<div class="todo" data-id="' + t.id + '"><span class="' + (t.done ? 'done' : '') + '">' + t.text + '</span></div>'
        ).join('');
        [...list.children].forEach((el) => {
          el.onclick = () => {
            const todo = todos.find((t) => t.id === el.dataset.id);
            todo.done = !todo.done;
            render();
          };
        });
      }
      document.getElementById('add').onclick = () => {
        if (!input.value.trim()) return;
        todos.unshift({ id: String(Date.now()), text: input.value.trim(), done: false });
        input.value = '';
        render();
      };
      render();
    </script>
  </body>
</html>`;

function createId() {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function summarize(text: string) {
  const cleaned = text.replace(/\s+/g, ' ').trim();
  return cleaned.length > 48 ? `${cleaned.slice(0, 48)}…` : cleaned || 'New chat';
}

const ChatStoreContext = createContext<ChatStoreValue | null>(null);

export function ChatStoreProvider({ children }: { children: React.ReactNode }) {
  const [chats, setChats] = useState<ChatHistoryItem[]>([]);
  const [activeChatId, setActiveChatId] = useState<string | null>(null);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [files, setFiles] = useState<ProjectFile[]>([]);
  const [previewHtml, setPreviewHtml] = useState('');
  const [input, setInput] = useState('');
  const [chatStarted, setChatStarted] = useState(false);
  const [isStreaming, setIsStreaming] = useState(false);
  const [showChat, setShowChat] = useState(true);
  const [showWorkbench, setShowWorkbench] = useState(false);
  const [selectedView, setSelectedView] = useState<'code' | 'preview'>('code');
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [enhancingPrompt, setEnhancingPrompt] = useState(false);
  const [promptEnhanced, setPromptEnhanced] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [description, setDescription] = useState('');
  const [streamTimer, setStreamTimer] = useState<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    AsyncStorage.getItem(HISTORY_KEY)
      .then((raw) => {
        if (!raw) return;
        try {
          const parsed = JSON.parse(raw) as ChatHistoryItem[];
          setChats(parsed);
        } catch {
          // ignore corrupt storage
        }
      })
      .catch(() => {
        // Keep an empty history when storage is unavailable.
      });
  }, []);

  const persistChats = useCallback((next: ChatHistoryItem[]) => {
    setChats(next);
    AsyncStorage.setItem(HISTORY_KEY, JSON.stringify(next)).catch(() => {
      // Ignore persistence failures; in-memory chat state still updates.
    });
  }, []);

  const startNewChat = useCallback(() => {
    if (streamTimer) {
      clearTimeout(streamTimer);
      setStreamTimer(null);
    }
    setActiveChatId(null);
    setMessages([]);
    setFiles([]);
    setPreviewHtml('');
    setInput('');
    setChatStarted(false);
    setIsStreaming(false);
    setShowChat(true);
    setShowWorkbench(false);
    setSelectedView('code');
    setSelectedFile(null);
    setPromptEnhanced(false);
    setDescription('');
    setSidebarOpen(false);
  }, [streamTimer]);

  const loadChat = useCallback(
    (id: string) => {
      const chat = chats.find((item) => item.id === id);
      if (!chat) return;
      setActiveChatId(chat.id);
      setMessages(chat.messages);
      setFiles(chat.files);
      setPreviewHtml(chat.previewHtml);
      setChatStarted(true);
      setShowWorkbench(chat.files.length > 0);
      setSelectedFile(chat.files[0]?.path ?? null);
      setSelectedView(chat.previewHtml ? 'preview' : 'code');
      setDescription(chat.description);
      setSidebarOpen(false);
      setShowChat(true);
    },
    [chats],
  );

  const deleteChat = useCallback(
    (id: string) => {
      const next = chats.filter((item) => item.id !== id);
      persistChats(next);
      if (activeChatId === id) {
        startNewChat();
      }
    },
    [activeChatId, chats, persistChats, startNewChat],
  );

  const enhancePrompt = useCallback(async () => {
    if (!input.trim() || enhancingPrompt) return;
    setEnhancingPrompt(true);
    await new Promise((resolve) => setTimeout(resolve, 900));
    setInput(
      `Build a polished mobile-friendly version of: ${input.trim()}. Use React Native with Tailwind-like styling, clear hierarchy, and a working interactive preview.`,
    );
    setPromptEnhanced(true);
    setEnhancingPrompt(false);
  }, [enhancingPrompt, input]);

  const stopStreaming = useCallback(() => {
    if (streamTimer) {
      clearTimeout(streamTimer);
      setStreamTimer(null);
    }
    setIsStreaming(false);
  }, [streamTimer]);

  const updateFileContent = useCallback((path: string, content: string) => {
    setFiles((current) => current.map((file) => (file.path === path ? { ...file, content } : file)));
  }, []);

  const sendMessage = useCallback(
    async (text?: string) => {
      const messageText = (text ?? input).trim();
      if (!messageText || isStreaming) return;

      const userMessage: ChatMessage = { id: createId(), role: 'user', content: messageText };
      const nextMessages = [...messages, userMessage];
      const chatId = activeChatId ?? createId();
      const chatDescription = description || summarize(messageText);

      setInput('');
      setPromptEnhanced(false);
      setChatStarted(true);
      setIsStreaming(true);
      setActiveChatId(chatId);
      setDescription(chatDescription);
      setMessages(nextMessages);
      setShowWorkbench(true);
      setSelectedView('code');

      const assistantId = createId();
      const fullReply = `I'll create that for you.

**Bolt Artifact**
- Scaffold a React Native todo app
- Add interactive preview
- Open the workbench so you can edit code on mobile

Your prompt: "${messageText}"

The project is ready in the workbench. Switch between **Code** and **Preview** to iterate.`;

      setMessages((current) => [...current, { id: assistantId, role: 'assistant', content: '' }]);

      let index = 0;
      const tick = () => {
        index += Math.max(3, Math.floor(fullReply.length / 40));
        const partial = fullReply.slice(0, index);
        setMessages((current) =>
          current.map((message) => (message.id === assistantId ? { ...message, content: partial } : message)),
        );

        if (index < fullReply.length) {
          const timer = setTimeout(tick, 40);
          setStreamTimer(timer);
          return;
        }

        setFiles(EXAMPLE_APP_FILES);
        setPreviewHtml(PREVIEW_HTML);
        setSelectedFile(EXAMPLE_APP_FILES[0].path);
        setSelectedView('preview');
        setShowChat(false);
        setShowWorkbench(true);
        setIsStreaming(false);
        setStreamTimer(null);

        const completedMessages: ChatMessage[] = [
          ...nextMessages,
          { id: assistantId, role: 'assistant', content: fullReply },
        ];
        const item: ChatHistoryItem = {
          id: chatId,
          description: chatDescription,
          createdAt: new Date().toISOString(),
          messages: completedMessages,
          files: EXAMPLE_APP_FILES,
          previewHtml: PREVIEW_HTML,
        };
        const remaining = chats.filter((chat) => chat.id !== chatId);
        persistChats([item, ...remaining]);
      };

      const timer = setTimeout(tick, 120);
      setStreamTimer(timer);
    },
    [activeChatId, chats, description, input, isStreaming, messages, persistChats],
  );

  const value = useMemo<ChatStoreValue>(
    () => ({
      chats,
      activeChatId,
      messages,
      files,
      previewHtml,
      input,
      chatStarted,
      isStreaming,
      showChat,
      showWorkbench,
      selectedView,
      selectedFile,
      enhancingPrompt,
      promptEnhanced,
      sidebarOpen,
      description,
      setInput,
      setSidebarOpen,
      setShowChat,
      setShowWorkbench,
      setSelectedView,
      setSelectedFile,
      startNewChat,
      loadChat,
      deleteChat,
      enhancePrompt,
      sendMessage,
      stopStreaming,
      updateFileContent,
    }),
    [
      chats,
      activeChatId,
      messages,
      files,
      previewHtml,
      input,
      chatStarted,
      isStreaming,
      showChat,
      showWorkbench,
      selectedView,
      selectedFile,
      enhancingPrompt,
      promptEnhanced,
      sidebarOpen,
      description,
      startNewChat,
      loadChat,
      deleteChat,
      enhancePrompt,
      sendMessage,
      stopStreaming,
      updateFileContent,
    ],
  );

  return <ChatStoreContext.Provider value={value}>{children}</ChatStoreContext.Provider>;
}

export function useChatStore() {
  const ctx = useContext(ChatStoreContext);
  if (!ctx) {
    throw new Error('useChatStore must be used within ChatStoreProvider');
  }
  return ctx;
}
